### ISSUE TITLE
zsh: command not found: sepolicy-inject

### ISSUE THREAD

**Issue by hongfeiyucode** [xmikos/setools-android#10]
Why am I running this command (Ubuntu 16.04 amd64)
```
Git clone https://github.com/xmikos/setools-android.git
Cd setools-android
Ndk-build
```
I still can not run `sepolicy-inject`
```
zsh: command not found: sepolicy-inject
zsh: There is no file or directory: ./sepolicy-inject
```
Which folder should I run this command?

Is there anything else that needs to be installed?

**Comment by lightydo** [comment]
the executables are in setools-android/libs/<arch>/

copy them to your phone to /system/xbin
you need to copy the rights one for your phone architecture.

**Comment by hongfeiyucode** [comment]
thank you very much

**Comment by luzhonghua0224** [comment]
How to copy the sepolicy-inject to /system/xbin without root permission?

**Comment by hongfeiyucode** [comment]
adb
