### ISSUE TITLE
Can't compile for X86_64

### ISSUE THREAD

**Issue by MaxChinni** [xmikos/setools-android#4]
Hi,
  I was trying to compile the project for multiple architectures following the documentation for x86_64 I found [here](http://brian.io/android-ndk-r10c-docs/Programmers_Guide/html/md_3__key__topics__c_p_u__support__c_p_u-_x86-64.html).
It states that adding `x86-64` to the `APP_ABI` definition in `Application.mk` should be sufficient, but I found that the right value seems to be `x86_64`.

With the following change, I receive an error anyway

    diff --git a/jni/Application.mk b/jni/Application.mk
    index 86c47ba..b3b0a55 100644
    --- a/jni/Application.mk
    +++ b/jni/Application.mk
    @@ -1,2 +1,2 @@
    -#APP_ABI := all
    +APP_ABI := x86_64
     APP_PLATFORM := android-16

Here's the error message

    [x86_64] Compile        : qpol <= util.c
    In file included from jni/libqpol/util.c:32:0:
    jni/libqpol/glob.h:40:24: fatal error: sys/_types.h: No such file or directory
     #include <sys/_types.h>
                            ^
    compilation terminated.
    make: *** [obj/local/x86_64/objs/qpol/util.o] Error 1

Am I missing something?

**Comment by xmikos** [comment]
New version 1.2 builds for arm64-v8a, mips64 and x86_64 without problems.

**Comment by MaxChinni** [comment]
I tried it and it works!

Thank you.
